name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  prepare_variables:
    runs-on: ubuntu-latest
    outputs:
      php_version: ${{ steps.variables.outputs.php_version }}
    steps:
      - name: Set variable outputs
        uses: actions/github-script@v6
        id: variables
        with:
          script: |
            core.setOutput('php_version', '${{ github.ref_name }}'.replaceAll(/[\w\.]+(\-?php)/g, ''))

  push_to_registry:
    name: Push Docker Image to DockerHub
    runs-on: ubuntu-latest
    needs: [prepare_variables]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: idecardo/docker-php-deployer-test
          tags: |
            type=ref,event=tag,enable=true
            type=raw,value=latest,enable={{ is_default_branch }}

      - name: Build and push Docker image to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PHP_VERSION=${{ needs.prepare_variables.outputs.php_version }}
