name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  php_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.php.outputs.version }}
    steps:
      - name: Set Global Variables for PHP Version
        uses: actions/github-script@v6
        id: php
        with:
          script: core.setOutput('version', '${{ github.ref_name }}'.replaceAll(/^(v)|(\-?dpd.*)/g, ''))

  push_to_registry:
    name: Push Docker Image to DockerHub
    runs-on: ubuntu-latest
    needs: [php_version]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: idecardo/docker-php-deployer-test

      - name: Build and push Docker image to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PHP_VERSION=${{ needs.php_version.outputs.version }}
